### PR TITLE
add (id)parameter to draggingBlocks.  UIView self can be called in draggingBlocks

### PR DESCRIPTION
**Pull request by jeffssss**
In my situation, I need to change UIView itself in draggingBlocks. And I think add (id self) in draggingBlocks is helpful. 

I'm not sure if there is any problem with it, and these code run well in my app. If I'm wrong , please tell me. Thank you

### CODE REVIEW

**Comment by andreamazz** [comment]
Hi @jeffssss 
The PR looks good, but I rather use typed parameters instead of `id`. So that would be `UIView`.
Also, can you update the test suite? If you're not too confident with it I can do it instead, let me know.

**Comment by jeffssss** [comment]
You are right. Typed parameters `UIView` is better. And I'm glad to do this. One question is that, What is `test suite` ? (my poor english  T_T)  Is that means I need to update `UIViewDraggableDemo` code to show this feature ?

**Comment by andreamazz** [comment]
I mean the tests in the demo app:
https://github.com/andreamazz/UIView-draggable/blob/master/UIViewDraggableDemo/UIViewDraggableDemoTests/UIViewDraggableDemoTests.m#L158
https://github.com/andreamazz/UIView-draggable/blob/master/UIViewDraggableDemo/UIViewDraggableDemoTests/UIViewDraggableDemoTests.m#L169
https://github.com/andreamazz/UIView-draggable/blob/master/UIViewDraggableDemo/UIViewDraggableDemoTests/UIViewDraggableDemoTests.m#L234

**Comment by jeffssss** [comment]
I didn't use Test before but I'll try my best. Please review my code after I finish this part of `test suite`. Thank you for your patience.

**Comment by andreamazz** [comment]
No problem, thanks for your work :+1:

**Comment by jeffssss** [comment]
I modify 3 cases you mentioned before and add `should call dragging moved block` case in Test file. And "Test success" is shown after I run the test. I think it's ok.

One question is, after I fork this project and open `UIViewDraggableDemo.xcworkspace`, an error occurred: `"Expecta+Snapshots/EXPMatchers+FBSnapshotTest.h"` file not found in `UIViewDraggableDemoTests.m`. 
There's something wrong with environment setting. And I solve this by delete `use_frameworks!` in Podfile and use 'pod install' to rebuild xcworkspace file. But it's not the right way to solve this problem. Do you have any good solution?

**Comment by andreamazz** [comment]
:+1:

**Comment by andreamazz** [comment]
Merged and released in `1.1.0`

**Pull request merged**
